version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...

  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo Build completed on `date`

# Include only the files required for your application to run.
artifacts:
  files:
    - index.js
    - package*.json
    - appspec.yml
    - '*/*.sh'
